name: CI (build & push)

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  IMAGE_NAME: andreas-app

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (cache npm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Compute tag
        id: meta
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build image (multi-stage)
        run: |
          docker build -t ${{ secrets.ACR_URL }}/${{ env.IMAGE_NAME }}:latest \
                       -t ${{ secrets.ACR_URL }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.TAG }} .

      - name: Push image
        run: |
          docker push ${{ secrets.ACR_URL }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.ACR_URL }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.TAG }}
